name: Project Deployment
on: [push, workflow_dispatch]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Installing node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm install
      - name: Running lint step
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing Dependencies
        run: npm install
      - name: Run frontend tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying artifact to Server
      - run: echo "Releasing to Production..."
