name: Deploy Project
on:
  push:
    branches:
      - 'basic-react-github-workflow'
  workflow_dispatch:
    branches:
      - 'basic-react-github-workflow'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Latest Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Frontend tests
        run: npm run test

  deploy:
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Latest Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying... build artifact to Cloud"
